import { FormControl, IconButton, Input, InputAdornment, InputLabel } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Search from '@mui/icons-material/Search';
import SendIcon from '@mui/icons-material/Send';
import { useState } from 'react';
import Link from 'next/link';

export default function Home() {

  const [userValue, setUserValue] = useState("")

  function getInputValue(event){
    setUserValue(event.target.value)
  }

  function handleSearch(event){
    <meta http-equiv="refresh" content={`2;url=/profile/${userValue}`}></meta>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <FormControl variant="standard">
          <Input
            className="myDiv"
            onChange={getInputValue}
            placeholder="Enter a Username"
            id="input-with-icon-adornment"
            onKeyPress={(e) => {
              if (e.key === 'Enter') {
                <Link href={`/profile/${userValue}`}></Link>
              }
            }}
            startAdornment={
              <InputAdornment position="start">
                <Search/>
              </InputAdornment>
            }
            endAdornment={
              <InputAdornment position="end">
                <Link href={`/profile/${userValue}`}>
                  <IconButton
                    aria-label="toggle password visibility"
                    edge="end"
                  >
                  <SendIcon/>
                  </IconButton>
                </Link>
              </InputAdornment>
            }
          />
        </FormControl>
      </main>
    </div>
  )
}
